"""replace unique constraint with partial index

Revision ID: 12710e4f9028
Revises: 384a9431ddc1
Create Date: 2026-03-02 03:27:00.394682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12710e4f9028'
down_revision: Union[str, Sequence[str], None] = '384a9431ddc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tenant_name'), 'tenants', type_='unique')
    op.create_index('uq_tenant_name_active', 'tenants', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tenant_name_active', table_name='tenants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_tenant_name'), 'tenants', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
