"""add slug to tenants

Revision ID: 29504d55f9f8
Revises: aa7e8946598c
Create Date: 2026-03-03 15:39:39.060959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29504d55f9f8'
down_revision: Union[str, Sequence[str], None] = 'aa7e8946598c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('slug', sa.String(length=100), nullable=False))
    op.drop_index(op.f('uq_tenant_name_active'), table_name='tenants', postgresql_where='(deleted_at IS NULL)')
    op.create_index('uq_tenant_name_active', 'tenants', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tenant_name_active', table_name='tenants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('uq_tenant_name_active'), 'tenants', ['name'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('tenants', 'slug')
    # ### end Alembic commands ###
