"""add ai processing fields

Revision ID: 3734bce79eb6
Revises: d123c96bcccb
Create Date: 2026-04-03 18:23:27.461622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3734bce79eb6'
down_revision: Union[str, Sequence[str], None] = 'd123c96bcccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('shipments', sa.Column('ai_processed', sa.Boolean(), nullable=True))
    op.add_column('shipments', sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True))

    op.execute("UPDATE shipments SET ai_processed = false")
    op.alter_column('shipments', 'ai_processed', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('shipments', 'ai_processed_at')
    op.drop_column('shipments', 'ai_processed')
    # ### end Alembic commands ###
