"""rename_delivery_date_to_expected_delivery_date

Revision ID: 51d71267be31
Revises: 87a63c4deefb
Create Date: 2026-04-13 16:33:01.869587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51d71267be31'
down_revision: Union[str, Sequence[str], None] = '87a63c4deefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'delivery_date', new_column_name='expected_delivery_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'expected_delivery_date', new_column_name='delivery_date')
    # ### end Alembic commands ###
