"""add index tenant_created_at

Revision ID: 57f148011026
Revises: dbbac73840fd
Create Date: 2026-04-08 15:57:08.387293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f148011026'
down_revision: Union[str, Sequence[str], None] = 'dbbac73840fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shipment_tenant_created_at', 'shipments', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipment_tenant_created_at', table_name='shipments')
    # ### end Alembic commands ###
