"""add shipment created_by

Revision ID: 7b7b4878bceb
Revises: d8f2a127350f
Create Date: 2026-05-16 17:11:29.413995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b7b4878bceb'
down_revision: Union[str, Sequence[str], None] = 'd8f2a127350f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shipments', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'created_by')
    
    # ### end Alembic commands ###
