"""add index to tenant_id

Revision ID: c182fa5d832e
Revises: ef8d6c95f62c
Create Date: 2026-04-08 15:47:10.356538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c182fa5d832e'
down_revision: Union[str, Sequence[str], None] = 'ef8d6c95f62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shipments_tenant_id'), 'shipments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_tenant_id'), table_name='shipments')
    # ### end Alembic commands ###
