"""add embedding column

Revision ID: c693b4c23e3c
Revises: 57f148011026
Create Date: 2026-04-12 13:32:40.040674

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c693b4c23e3c'
down_revision: Union[str, Sequence[str], None] = '57f148011026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments',sa.Column('embedding', Vector(1536), nullable=True))
    op.drop_index(op.f('Shipment_tracking_number'), table_name='shipments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('Shipment_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.drop_column('shipments', 'embedding')
    # ### end Alembic commands ###
