"""make audit ip nullable

Revision ID: da0fd11779e0
Revises: 21b2f9403a73
Create Date: 2026-05-12 18:18:43.009827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0fd11779e0'
down_revision: Union[str, Sequence[str], None] = '21b2f9403a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # ### end Alembic commands ###
