"""add composite index tenant_id_status

Revision ID: dbbac73840fd
Revises: c182fa5d832e
Create Date: 2026-04-08 15:50:14.402113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbac73840fd'
down_revision: Union[str, Sequence[str], None] = 'c182fa5d832e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shipments_tenant_status', 'shipments', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipments_tenant_status', table_name='shipments')
    # ### end Alembic commands ###
