"""add pickup_date, delivery_date, description to shipments

Revision ID: e751eef839fc
Revises: 87f39c5e3e4d
Create Date: 2026-03-28 19:22:37.994167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e751eef839fc'
down_revision: Union[str, Sequence[str], None] = '87f39c5e3e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipments', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))

    # Backfill existing rows with default values
    op.execute("UPDATE shipments SET description = 'No description' WHERE description IS NULL")
    op.execute("UPDATE shipments SET pickup_date = NOW() WHERE pickup_date IS NULL")
    op.execute("UPDATE shipments SET delivery_date = NOW() WHERE delivery_date IS NULL")

    # Now make columns non-nullable
    op.alter_column('shipments', 'description', nullable=False)
    op.alter_column('shipments', 'pickup_date', nullable=False)
    op.alter_column('shipments', 'delivery_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'delivery_date')
    op.drop_column('shipments', 'pickup_date')
    op.drop_column('shipments', 'description')
    # ### end Alembic commands ###
