"""add index to tracking_number

Revision ID: ef8d6c95f62c
Revises: fd20068c4805
Create Date: 2026-04-08 15:43:29.153306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef8d6c95f62c'
down_revision: Union[str, Sequence[str], None] = 'fd20068c4805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('shipments', 'pickup_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('shipments', 'delivery_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.drop_column('shipments', 'update_at')
    op.alter_column('shipments_status_log', 'updated_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments_status_log', 'updated_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('shipments', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.alter_column('shipments', 'delivery_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('shipments', 'pickup_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('shipments', 'updated_at')
    # ### end Alembic commands ###
